### ISSUE TITLE
missing some GUI features from 0.6.2...

### ISSUE THREAD

**Issue by Vasilich** [RazrFalcon/svgcleaner-gui#1]
Hi RazrFalcon,
while algorithms of 0.6.9 are better that 0.6.2 (i believe your charts on home page :) ), there are some features that i miss from 062:
-    no preview before/after
-    no possibility to save result to source dir with prefix/postfix

Is there any chance to get it in new GUI?

**Comment by RazrFalcon** [comment]
Hello.
1. No. This is not possible. QtSvg, which was used before, supports only tiny part of an SVG spec. You can't tell that the file is broken using it. Only way is to use QtWebKit fork, since original QtWebKit is deprecated, but it's pain to distribute, it's very big and slow. Currently there are now way to implement this.
2. It's possible, but is it really needed? It's a bit pain to implement.

**Comment by Vasilich** [comment]
1. ok, understood :(
2. Yes, please. I have used it 2 years with this setting and get used to it :) And now, when there is no before/after preview, it is easier to do it in the same folder, where both files are near to each other.

**Comment by RazrFalcon** [comment]
Implemented.
