### ISSUE TITLE
Compare raster images

### ISSUE THREAD

**Issue by RazrFalcon** [RazrFalcon/svgcleaner-gui#2]
Problems:
- QtWebKit is huge and outdated, so we need to use it's [fork](https://github.com/annulen/webkit). Witch is pain to distribute.
- QtWebEngine is even bigger and doesn't support printing yet.
- QtWebKit has rendering bugs...

**Comment by polarathene** [comment]
QtWebEngine should be able to print to PDF now. QtWebKit I think also had improvements since you originally created this issue?

An alternative would be to rasterize the SVGs outside of either option as well? Or couldn't you just display both SVG in a webview without converting them to raster images?

**Comment by RazrFalcon** [comment]
It will be very slow. And Blink isn't [that good](https://razrfalcon.github.io/resvg-test-suite/svg-support-table.html#_tests_summary) anyway.

Also, I'm not sure why this task is still open. There are no point in this.

**Comment by RazrFalcon** [comment]
Out of scope.
